fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    view:
        view_response_listener:  true

    serializer:
      serialize_null: true

    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors

    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
