nelmio_api_doc:
    documentation:
        info:
            title: Acme corp REST API
            description: RTB House ☕️
            version: "v1.0.0"
    areas:
        path_patterns:
            - ^/api(?!/doc$)
